#lang racket
(define (expt-multip a b)
  (if(= b 0)
     0
     (+ a (expt-multip a (- b 1)))
   )
  )
(define (even? a)
   (= (remainder a 2)0)
  )
(define (double a)
  (+ a a)
 )
(define (halve a)
  (if(even? a)
     (/ a 2)
      (display "wrong!")
     )
  )
(define (my-expt-multip a b )
  (display "a")
  (cond ((= b 1) a)
         ((even? b) (my-expt-multip (double a) (halve b) ) )
        (else (+ a (my-expt-multip a (- b 1) )))
   )
  
  )
(define (my-expt-start a b) (my-expt-multip a b a))
(my-expt-multip 46 1000)