#lang racket
(define (double x) (+ x x))
(define (halve x)  (/ x 2))
(define (even? x)  (= (remainder x 2)0))
(define (fast-expt-first b n a)
  (cond ((= n 0)1)
         ((= n 1)(* b a))
         ((even? n) (fast-expt-first (* b b) (/ n 2) a))
         (else (fast-expt-first b (- n 1) (* a b))
         )))
(define (fast-expt b n) (fast-expt-first b n 1))
;↑fast-expt function


(define (=number? exp num) (and (number? exp) (= exp num)))
(define (variable? x) (symbol? x))
(define (same-variable? x y) (and (variable? x ) (variable? y) (equal? x y )))
(define (addend s) (cadr s))
(define (augend s) (cadr (cdr s)))
(define (make-sum a1 a2)(cond ((=number? a1 0) a2)
                              ((=number? a2 0) a1)
                              ((and (number? a1) (number? a2)) (+ a1 a2))
                              (else (list '+ a1 a2))))
(define (sum? x) (and (pair? x)(equal? '+ (car x))))

(define (make-product a1 a2) (cond ((or (=number? a1 0) (=number? a2 0)) 0)
                                   ((=number? a1 1) a2)
                                   ((=number? a2 1) a1)
                                   ((and (number? a1) (number? a2)) (* a1 a2))
                                   (else (list '* a1 a2))))
(define (product? s) (and (equal? '* (car s)) (pair? s)))
(define (multiplier s) (cadr s))
(define (multiplicand s) (caddr s))
(define (make-exponentiation var times) (cond ((and (number? var) (number? times)) (fast-expt var times))
                                              ((=number? times 0) 1)
                                              ((=number? times 1) var)
                                              (else (list '** var times)) ))
(define (exponentiation? s) (and (equal? '** (car s)) (pair? s)))
(define (base s) (cadr s))
(define (exponent s) (caddr s))

(define (deriv exp var)
  (cond ((number? exp) 0)
        ((variable? exp)
         (if (same-variable? exp var) 1 0))
        ((sum? exp)
         (make-sum (deriv (addend exp) var) (deriv (augend exp) var)))
        ((product? exp) (make-sum (make-product (multiplier exp) (deriv (multiplicand exp) var)) (make-product (deriv (multiplier exp) var) (multiplicand exp))))
        ((exponentiation? exp) (make-product (make-product (exponent exp) (make-exponentiation (base exp) (make-sum (exponent exp) -1);use make-sum instead of (- (exponent exp) 1) to fit  (list '** 'x 'x)
                                                                                               )) (deriv (base exp) var)))
        (else (error exp))))
(deriv (list '** 'x 4) 'x)
